# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/uCOS-II/uCOS-II.srcs/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ.xci
# IP: The module: 'clk_wiz_25MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/uCOS-II/uCOS-II.gen/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25MHZ'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/uCOS-II/uCOS-II.gen/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/uCOS-II/uCOS-II.gen/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/uCOS-II/uCOS-II.srcs/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ.xci
# IP: The module: 'clk_wiz_25MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/uCOS-II/uCOS-II.gen/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/uCOS-II/uCOS-II.gen/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/uCOS-II/uCOS-II.gen/sources_1/ip/clk_wiz_25MHZ/clk_wiz_25MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_25MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
