@startuml
start

:注册/登录;
:编辑个人资料与乘车偏好;
:绑定支付方式;
:输入起始地、目的地、出发时间;
:搜索拼车邀请;
if (存在匹配方案?) then (是)
  :选择拼车方案并接单;
else (否)
  :生成拼车需求记录;
endif
:进入订单管理;
:查看行程状态/修改/取消/投诉;
:行程开始，实时查看车辆位置;
:行程结束，系统推送支付通知;
:完成支付;
:对车主评价与反馈;
:管理员处理反馈并回传结果;

stop
@enduml