@startuml
actor 乘客
participant 用户系统
participant 交易系统
participant 行程管理系统
participant 信息交互系统
actor 管理人员

乘客 -> 用户系统 : 注册/登录
用户系统 -> 乘客 : 成功

乘客 -> 用户系统 : 编辑个人资料/偏好/绑定支付
乘客 -> 行程管理系统 : 搜索行程
行程管理系统 -> 乘客 : 成功匹配行程

乘客 -> 交易系统 : 接收支付通知
交易系统 -> 乘客 : 支付接车费用

乘客 -> 信息交互系统 : 拼车意见反馈
信息交互系统 -> 管理人员 : 收到反馈信息
管理人员 -> 信息交互系统 : 处理反馈信息
信息交互系统 -> 乘客 : 处理反馈结果

@enduml