@startuml
actor 车主
participant 用户系统
participant 交易系统
participant 行程管理系统
participant 信息交互系统
actor 管理人员

车主 -> 用户系统 : 注册/登录
用户系统 -> 车主 : 成功

车主 -> 用户系统 : 认证驾驶资格
用户系统 -> 行程管理系统 : 审核资料
行程管理系统 -> 用户系统 : 审核结果
用户系统 -> 车主 : 成功

车主 -> 行程管理系统 : 发布行程
行程管理系统 -> 车主 : 接单行程

车主 -> 交易系统 : 获取接单费用
交易系统 -> 车主 : 接单费用到账

车主 -> 信息交互系统 : 拼车意见反馈
信息交互系统 -> 管理人员 : 收到反馈信息
管理人员 -> 信息交互系统 : 处理反馈信息
信息交互系统 -> 车主 : 处理反馈信息

@enduml